<?php
session_start();//KEEP IN MIND TO UNSET SESSION VARIABLES SO THAT USER DOESNT GET REDIRECTED TO SITE AFTER PRESSING BACK BUTTON WE NEED TO UNSET
//ALL SESSION VARIABLES AND FOR THAT unset(); IS USED.ALSO WE SHOULD START SESSION ON LOGOUT PAGE SO THAT ALL SESSION VARIABLES FROM OTHER
//PAGES CAN BE FETCHED BY US

 unset($_SESSION['email_of_user']);
 unset($_SESSION['user_id']);
 session_destroy();
 header('location:login.php');
?>